apiVersion: v1
kind: Service
metadata:
  labels:
    app: giphyneitor
  name: giphyneitor
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: giphyneitor
  type: ClusterIP